// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4FAcey5dYcejqa3mgfw6imhqqatcWLlk',
    appId: '1:45885419874:web:e1fefa8508e5cf8664bc3b',
    messagingSenderId: '45885419874',
    projectId: 'finki-lab4-mis',
    authDomain: 'finki-lab4-mis.firebaseapp.com',
    storageBucket: 'finki-lab4-mis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDllzSzYVe0XcCsRQx4ZnSSsYvqK_TTYOU',
    appId: '1:45885419874:android:28b9c7846520aa1c64bc3b',
    messagingSenderId: '45885419874',
    projectId: 'finki-lab4-mis',
    storageBucket: 'finki-lab4-mis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8FYdpO92inO7vC0Q3ctIaV14UEDmfcpM',
    appId: '1:45885419874:ios:bc167b7a4162fbe264bc3b',
    messagingSenderId: '45885419874',
    projectId: 'finki-lab4-mis',
    storageBucket: 'finki-lab4-mis.appspot.com',
    iosClientId: '45885419874-gp8qschaiv876a14vf7vrv8ng1sr2s7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab4Test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8FYdpO92inO7vC0Q3ctIaV14UEDmfcpM',
    appId: '1:45885419874:ios:bc167b7a4162fbe264bc3b',
    messagingSenderId: '45885419874',
    projectId: 'finki-lab4-mis',
    storageBucket: 'finki-lab4-mis.appspot.com',
    iosClientId: '45885419874-gp8qschaiv876a14vf7vrv8ng1sr2s7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab4Test',
  );
}
